/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as ConceptsIndexRouteImport } from './routes/concepts/index'
import { Route as RulesSlugRouteImport } from './routes/rules/$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as ConceptsSlugRouteImport } from './routes/concepts/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsIndexRoute = ConceptsIndexRouteImport.update({
  id: '/concepts/',
  path: '/concepts/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesSlugRoute = RulesSlugRouteImport.update({
  id: '/rules/$slug',
  path: '/rules/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsSlugRoute = ConceptsSlugRouteImport.update({
  id: '/concepts/$slug',
  path: '/concepts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/rules/$slug': typeof RulesSlugRoute
  '/concepts': typeof ConceptsIndexRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/rules/$slug': typeof RulesSlugRoute
  '/concepts': typeof ConceptsIndexRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/rules/$slug': typeof RulesSlugRoute
  '/concepts/': typeof ConceptsIndexRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/concepts/$slug'
    | '/guides/$slug'
    | '/rules/$slug'
    | '/concepts'
    | '/guides'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/concepts/$slug'
    | '/guides/$slug'
    | '/rules/$slug'
    | '/concepts'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/concepts/$slug'
    | '/guides/$slug'
    | '/rules/$slug'
    | '/concepts/'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConceptsSlugRoute: typeof ConceptsSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  RulesSlugRoute: typeof RulesSlugRoute
  ConceptsIndexRoute: typeof ConceptsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/': {
      id: '/concepts/'
      path: '/concepts'
      fullPath: '/concepts'
      preLoaderRoute: typeof ConceptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$slug': {
      id: '/rules/$slug'
      path: '/rules/$slug'
      fullPath: '/rules/$slug'
      preLoaderRoute: typeof RulesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/$slug': {
      id: '/concepts/$slug'
      path: '/concepts/$slug'
      fullPath: '/concepts/$slug'
      preLoaderRoute: typeof ConceptsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConceptsSlugRoute: ConceptsSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  RulesSlugRoute: RulesSlugRoute,
  ConceptsIndexRoute: ConceptsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
